### ISSUE TITLE
centos-rpm-test failing in scylla-3.1 due to folder_scylla_repo_file_url not set

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-artifact-tests#127] opened 2019-05-15 11:40 UTC
Seen in [scylla-3.1/job/centos-rpm-test/10/label=muninn/artifact/latest/job.log](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/centos-rpm-test/10/label=muninn/artifact/latest/job.log):

It looks like `folder_scylla_repo_file_url` is not set.

```
2019-05-15 02:57:57,027 process          L0333 INFO | Running 'sudo curl ${folder_scylla_repo_file_url}centos/master/10/scylla.repo -o /etc/yum.repos.d/scylla.repo -L'
2019-05-15 02:57:57,224 process          L0420 DEBUG| [stderr]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-05-15 02:57:57,225 process          L0420 DEBUG| [stderr]                                  Dload  Upload   Total   Spent    Left  Speed
2019-05-15 02:57:57,225 process          L0420 DEBUG| [stderr] 
2019-05-15 02:57:57,225 process          L0420 DEBUG| [stderr]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: centos; Unknown error
2019-05-15 02:57:57,226 stacktrace       L0036 ERROR| 
2019-05-15 02:57:57,226 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:436
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR| Traceback (most recent call last):
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py", line 765, in setUp
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|     self.scylla_setup()
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py", line 751, in scylla_setup
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|     installer.run()
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py", line 330, in run
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|     pkgs = self.env_setup()
2019-05-15 02:57:57,251 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py", line 573, in env_setup
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR|     self.download_scylla_repo()
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR|   File "/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py", line 322, in download_scylla_repo
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR|     shell=True)
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1031, in run
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
2019-05-15 02:57:57,252 stacktrace       L0042 ERROR| CmdError: Command 'sudo curl ${folder_scylla_repo_file_url}centos/master/10/scylla.repo -o /etc/yum.repos.d/scylla.repo -L' failed (rc=6)
2019-05-15 02:57:57,252 stacktrace       L0043 ERROR| 
2019-05-15 02:57:57,270 test             L0581 ERROR| ERROR 1-/root/avocado/tests/jenkins/slave/workspace/scylla-3.1/centos-rpm-test/label/muninn/scylla-artifacts.py:ScyllaArtifactSanity.test_after_install -> TestSetupFail: Command 'sudo curl ${folder_scylla_repo_file_url}centos/master/10/scylla.repo -o /etc/yum.repos.d/scylla.repo -L' failed (rc=6)
```

**Comment by bhalevy** [comment] 2019-05-15 11:49
`${folder_scylla_repo_file_url}` is used for `scylla_repo_file_url` in [https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/centos-rpm-test/lastFailedBuild/label=muninn/parameters/](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/centos-rpm-test/lastFailedBuild/label=muninn/parameters/)

There are also a couple other variable there that I'm not sure where they supposed to be defined: `folder_scylla_s3_path` and `folder_scylla_repo_file_url_update`

**Comment by roydahan** [comment] 2019-05-15 11:51
It's a problem with the job / or the params transferred to the job from the parent job.

**Closed by roydahan** 2019-05-15 11:51 UTC

**Comment by amoskong** [comment] 2019-05-16 05:14
It's caused by wrong configuration of http://jenkins.scylladb.com/job/scylla-3.1/job/centos-rpm/configure
